from services.fsq_analysis import FsqHandler
from services.lastfm_analysis import LastfmHandler
from services.movie_analysis import MovieHandler
from services.spotify_analysis import SpotifyHandler
from services.todoist_analysis import TaskHandler
from services.tastekid_analysis import TastekidHandler
from services.twitter_analysis import TwitterHandler